### ISSUE TITLE
New keyword DATEDIFF

### ISSUE THREAD

**Issue by rodrigorodriguez** [GeneralBots/BotServer#170]
days = DATEDIFF date1, date2, "days"

**Comment by rodrigorodriguez** [comment]
Added [DATEADD as well](https://github.com/GeneralBots/BotServer/commit/a011ec0a333ee97976b4c15e29a1372699625159).

**Comment by PH-Nascimento** [comment]
@rodrigorodriguez não funcionou com a sintaxe informada:
log:
2022-01-10T23:32:41.333Z [GeneralBots] [31merror[39m: ERROR: INVALID BASIC CODE: Unexpected token 'this' evalmachine.<anonymous>:1async function await this.dateDiff(step) {^^^^
SyntaxError: Unexpected token 'this'at new Script (vm.js:100:7)at createScript (vm.js:261:10)at Object.runInContext (vm.js:292:10)at Function.callVM (D:\home\site\wwwroot\dist\packages\basic.gblib\services\GBVMService.js:719:16)
at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at async GBMinService.processMessageActivity (D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:817:17)at async D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:705:21 Error: INVALID BASIC CODE: Unexpected token 'this' evalmachine.<anonymous>:1async function await this.dateDiff(step) {^^^^
SyntaxError: Unexpected token 'this'at new Script (vm.js:100:7)at createScript (vm.js:261:10)at Object.runInContext (vm.js:292:10)at Function.callVM (D:\home\site\wwwroot\dist\packages\basic.gblib\services\GBVMService.js:719:16)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at async GBMinService.processMessageActivity (D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:817:17)at async D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:705:21at Function.callVM (D:\home\site\wwwroot\dist\packages\basic.gblib\services\GBVMService.js:722:19)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at async GBMinService.processMessageActivity (D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:817:17)at async D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:705:21
2022-01-10T23:32:41.346Z [GeneralBots] [32minfo[39m: Translated text(sendText): Lamento, ocorreu um erro que já foi registrado para ser tratado..
2022-01-10T23:32:42.382Z [GeneralBots] [32minfo[39m: Message [Lamento, ocorreu um erro que já foi registrado para ser tratado.] sent to 5521979047667: {"sent":true,"message":"Sent to 5521979047667@c.us","id":"true_5521979047667@c.us_3EB07B80A0A02176184E","queueNumber":4952}

**Comment by PH-Nascimento** [comment]
talk “informe a data 1” 

hear data1 

talk “informe a data 2” 

hear data2 

dias = DATEDIFF data1, data2, "dias" 

talk “ a diferença de dias é: “ + dias 

exit
