### ISSUE TITLE
Comando Send file

### ISSUE THREAD

**Issue by PH-Nascimento** [GeneralBots/BotServer#173]
**Describe the bug**

Send file não executado quando dentro de uma condição no gbdialog.
https://dev.azure.com/pragmatismo-io/GeneralBotsOnline/_workitems/edit/1096

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PH-Nascimento** [comment]
Verificar latência de quase 1 minuto para envio do anexo, no send file.

**Comment by PH-Nascimento** [comment]
O send file quando executado dentro de um start dialog se apresenta como se estivesse pela web.
![image](https://user-images.githubusercontent.com/42078703/130774025-91e26483-56d4-4254-af09-1ef92610bcda.png)

**Comment by PH-Nascimento** [comment]
@rodrigorodriguez 
Não está sendo possível a realização de testes.
Já na chamada do Bot o spell checker separa as palavras.

2021-10-01T14:23:21.236Z [GeneralBots] [32minfo[39m: User>: text:**maispodologiabot** (type: message, name: undefined, channelId: webchat, value: undefined)
2021-10-01T14:23:21.407Z [GeneralBots] [32minfo[39m: **Spelling corrected (processMessageActivity)**: mais podologia bot
2021-10-01T14:23:21.532Z [GeneralBots] [32minfo[39m: Translated text (processMessageActivity): mais podologia bot.
2021-10-01T14:23:21.548Z [GeneralBots] [32minfo[39m: Final text ready for NLP/Search/.gbapp: mais podologia bot.
2021-10-01T14:23:21.595Z [GeneralBots] [32minfo[39m: Sending event stop:undefined to client...
2021-10-01T14:23:22.219Z [GeneralBots] [32minfo[39m: **SEARCH WILL NOT be used as answerId 229908 was not found in database,**
returnedScore: 0.7688495 < required (searchScore): 0.43
2021-10-01T14:23:22.312Z [GeneralBots] [32minfo[39m: NLP called: t, entities: undefined, score: 0.28620112 > required (nlpScore): 0.2
2021-10-01T14:23:22.500Z [GeneralBots][32minfo[39m: Translated text(sendText): Please wait while I locate someone to see you..
2021-10-01T14:23:24.481Z [GeneralBots] [32minfo[39m: Message [Please wait while I locate someone to see you.] sent to 5521979047667: {"sent":true,"message":"Sent to 5521979047667@c.us","id":"true_5521979047667@c.us_3EB0238BB032533E018F","queueNumber":345}
2021-10-01T14:23:24.512Z [GeneralBots] [31merror[39m: ERROR: Cannot read property 'split' of undefined TypeError: Cannot read property 'split' of undefinedat SecService.assignHumanAgent (D:\home\site\wwwroot\dist\packages\security.gbapp\services\SecService.js:155:46)at Array.<anonymous> (D:\home\site\wwwroot\dist\packages\customer-satisfaction.gbapp\dialogs\FeedbackDialog.js:77:49)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-10-01T14:23:24.700Z [GeneralBots] [32minfo[39m: Translated text(sendText): I'm sorry, there's been an error that's already been registered to be handled..
2021-10-01T14:23:25.472Z [GeneralBots] [32minfo[39m: Message [I'm sorry, there's been an error that's already been registered to be handled.] sent to 5521979047667: {"sent":true,"message":"Sent to 5521979047667@c.us","id":"true_5521979047667@c.us_3EB06F10A70142815AAF","queueNumber":346}

**Comment by PH-Nascimento** [comment]
@rodrigorodriguez pelo WhatsApp se comportando como se estivesse na web.

![image](https://user-images.githubusercontent.com/42078703/135644772-b18cc927-7b44-4cd8-81f1-413850b4925b.png)

2021-10-01T14:52:17.461Z [GeneralBots] [32minfo[39m: GBWhatsapp: RCV 5521979047667(PH): /start)
2021-10-01T14:52:17.492Z [GeneralBots] [32minfo[39m: GBWhatsapp: Starting new conversation on Bot.
2021-10-01T14:52:17.617Z [GeneralBots] [32minfo[39m: GBWhatsapp: Starting message polling(5521979047667, 79mLgWzTCOCIMgeDQRQqZS-o).
2021-10-01T14:52:17.632Z [GeneralBots] [32minfo[39m: Sending event loadInstance:{} to client...
2021-10-01T14:52:17.726Z [GeneralBots] [32minfo[39m: Sending event play:{"playerType":"bullet","data":[]} to client...
2021-10-01T14:52:17.851Z [GeneralBots] [32minfo[39m: User>: text:undefined (type: conversationUpdate, name: undefined, channelId: webchat, value: undefined)
2021-10-01T14:52:17.851Z [GeneralBots] [32minfo[39m: Bot added to conversation, starting chat...
2021-10-01T14:52:17.870Z [GeneralBots] [32minfo[39m: Auto start (web) dialog is now being called: Start for 304...
2021-10-01T14:52:17.898Z [GeneralBots] [32minfo[39m: Translated text(sendText): Olá! Bem vinda(o)!!.
2021-10-01T14:52:17.932Z [GeneralBots] [32minfo[39m: Sending event loadInstance:{} to client...
2021-10-01T14:52:18.007Z [GeneralBots] [32minfo[39m: BASIC: Sending the contents of novidades.md markdown to mobile null.
2021-10-01T14:52:18.040Z [GeneralBots] [32minfo[39m: Sending event play:{"playerType":"bullet","data":[]} to client...
2021-10-01T14:52:18.054Z [GeneralBots] [32minfo[39m: Translated text(playMarkdown):![*MaisPodologia*](kb/MaisPodologiaBot.gbai/MaisPodologiaBot.gbkb/images/maispodologo.png)
Olá! Tudo bem?
Eu sou o Bot da MaisPodologia e estou ao seu dispor 24 horas por dia.
Por enquanto você pode me perguntar coisas do tipo:
👉 *Unidades*
👉 *Tratamentos*
👉 *Agendamentos*
.
2021-10-01T14:52:18.088Z [GeneralBots] [32minfo[39m: Translated text(sendText): Vou te responder na tela para melhor visualização....
2021-10-01T14:52:18.195Z [GeneralBots] [32minfo[39m: Sending event play:{"playerType":"markdown","data":{"content":"<p><img src=\"https://prod-generalbots-server.azurewebsites.net/kb/MaisPodologiaBot.gbai/MaisPodologiaBot.gbkb/images/maispodologo.png\" alt=\"*MaisPodologia*\"></p>\n<p>Olá! Tudo bem?</p>\n<p>Eu sou o Bot da MaisPodologia e estou ao seu dispor 24 horas por dia.</p>\n<p>Por enquanto você pode me perguntar coisas do tipo:</p>\n<pre><code>👉 *Unidades*\n\n👉 *Tratamentos*\n\n👉 *Agendamentos*\n</code></pre>\n","answer":"\r\n![*MaisPodologia*](kb/MaisPodologiaBot.gbai/MaisPodologiaBot.gbkb/images/maispodologo.png)\r\n\r\nOlá! Tudo bem?\r\n\r\nEu sou o Bot da MaisPodologia e estou ao seu dispor 24 horas por dia.\r\n\r\nPor enquanto você pode me perguntar coisas do tipo:\r\n\r\n    👉 *Unidades*\r\n\r\n    👉 *Tratamentos*\r\n\r\n    👉 *Agendamentos*\r\n    \r\n","prevId":0,"nextId":0}} to client...
2021-10-01T14:52:18.242Z [GeneralBots] [32minfo[39m: User>: text:undefined (type: conversationUpdate, name: undefined, channelId: webchat, value: undefined)

**Comment by PH-Nascimento** [comment]
@rodrigorodriguez o problema continua.
![image](https://user-images.githubusercontent.com/42078703/136667804-7f6577f8-1c91-4fd5-b74f-ab80cd04d16f.png)

2021-10-09T17:04:04.314Z [GeneralBots] [32minfo[39m: Calling /start for Auto start : Start for MaisPodologiaBot...
2021-10-09T17:04:04.345Z [GeneralBots] [32minfo[39m: GBWhatsapp: RCV 5521979047667(PH): /start)
2021-10-09T17:04:04.376Z [GeneralBots] [32minfo[39m: GBWhatsapp: Starting new conversation on Bot.
2021-10-09T17:04:04.550Z [GeneralBots] [32minfo[39m: GBWhatsapp: Starting message polling(5521979047667, 9uC0eIkx7s55EggitaB07I-o).
2021-10-09T17:04:04.634Z [GeneralBots] [32minfo[39m: Sending event loadInstance:{} to client...
2021-10-09T17:04:04.773Z [GeneralBots] [32minfo[39m: Sending event loadInstance:{} to client...
2021-10-09T17:04:05.035Z [GeneralBots] [32minfo[39m: Sending event play:{"playerType":"bullet","data":[]} to client...
2021-10-09T17:04:05.079Z [GeneralBots] [32minfo[39m: Sending event play:{"playerType":"bullet","data":[]} to client...
2021-10-09T17:04:05.157Z [GeneralBots] [32minfo[39m: User>: text:undefined (type: conversationUpdate, name: undefined, channelId: webchat, value: undefined)
2021-10-09T17:04:05.188Z [GeneralBots] [32minfo[39m: Bot added to conversation, starting chat...
2021-10-09T17:04:05.204Z [GeneralBots] [32minfo[39m: Auto start (web) dialog is now being called: Start for 304...
2021-10-09T17:04:05.219Z [GeneralBots] [32minfo[39m: Translated text(sendText): Olá! Bem vinda(o)!!.
2021-10-09T17:04:05.282Z [GeneralBots] [32minfo[39m: User>: text:undefined (type: conversationUpdate, name: undefined, channelId: webchat, value: undefined)
2021-10-09T17:04:05.298Z [GeneralBots] [32minfo[39m: Person added to conversation: PH
2021-10-09T17:04:05.360Z [GeneralBots] [32minfo[39m: User>: text:/start (type: message, name: undefined, channelId: webchat, value: undefined)
2021-10-09T17:04:05.376Z [GeneralBots] [32minfo[39m: BASIC: Sending the contents of novidades.md markdown to mobile null.
2021-10-09T17:04:05.391Z [GeneralBots] [32minfo[39m: Translated text(playMarkdown):![*MaisPodologia*](kb/MaisPodologiaBot.gbai/MaisPodologiaBot.gbkb/images/maispodologo.png)
Olá! Tudo bem?
Eu sou o Bot da MaisPodologia e estou ao seu dispor 24 horas por dia.
Por enquanto você pode me perguntar coisas do tipo:
👉 *Unidades*
👉 *Tratamentos*
👉 *Agendamentos*
.
2021-10-09T17:04:05.407Z [GeneralBots] [32minfo[39m: Sending event play:{"playerType":"markdown","data":{"content":"<p><img src=\"https://prod-generalbots-server.azurewebsites.net/kb/MaisPodologiaBot.gbai/MaisPodologiaBot.gbkb/images/maispodologo.png\" alt=\"*MaisPodologia*\"></p>\n<p>Olá! Tudo bem?</p>\n<p>Eu sou o Bot da MaisPodologia e estou ao seu dispor 24 horas por dia.</p>\n<p>Por enquanto você pode me perguntar coisas do tipo:</p>\n<pre><code>👉 *Unidades*\n\n👉 *Tratamentos*\n\n👉 *Agendamentos*\n</code></pre>\n","answer":"\r\n![*MaisPodologia*](kb/MaisPodologiaBot.gbai/MaisPodologiaBot.gbkb/images/maispodologo.png)\r\n\r\nOlá! Tudo bem?\r\n\r\nEu sou o Bot da MaisPodologia e estou ao seu dispor 24 horas por dia.\r\n\r\nPor enquanto você pode me perguntar coisas do tipo:\r\n\r\n    👉 *Unidades*\r\n\r\n    👉 *Tratamentos*\r\n\r\n    👉 *Agendamentos*\r\n    \r\n","prevId":0,"nextId":0}} to client...
2021-10-09T17:04:09.614Z [GeneralBots] [32minfo[39m: GBWhatsapp: SND 5521979047667(PH): Olá! Bem vinda(o)!!
2021-10-09T17:04:10.547Z [GeneralBots] [32minfo[39m: Message [Olá! Bem vinda(o)!!] sent to 5521979047667: {"sent":true,"message":"Sent to 5521979047667@c.us","id":"true_5521979047667@c.us_3EB08B1517255529D401","queueNumber":441}

**Comment by PH-Nascimento** [comment]
OK! Liberado!
