### ISSUE TITLE
New BASIC keyword ACTIVE TASKS

### ISSUE THREAD

**Issue by rodrigorodriguez** [GeneralBots/BotServer#179]
list = ACTIVE TASKS should return all active tasks from all users in HubSpot.

**Comment by rodrigorodriguez** [comment]
Calling HUB SPOT from .gbdialog:


key = "ddcc3f4e-edfe-4dc5-a337-" 

talk “Obtendo tarefas do XRM...” 

dados = GET https://api.hubapi.com/engagements/v1/engagements/paged?hapikey= + key

**Comment by PH-Nascimento** [comment]
@rodrigorodriguez ocorrendo erro ao executar script:
![image](https://user-images.githubusercontent.com/42078703/149778370-eda39f75-01a2-44f5-98b5-60a78434b92b.png)



2022-01-17T13:32:35.306Z [GeneralBots] [32minfo[39m: GBWhatsapp: RCV 5521979047667(): /call hubspot)
2022-01-17T13:32:36.134Z [GeneralBots] [32minfo[39m: User>: text:/call hubspot (type: message, name: undefined, channelId: webchat, value: undefined)
2022-01-17T13:32:36.309Z [GeneralBots] [32minfo[39m: Translated text(sendText): Obtendo tarefas do XRM....
2022-01-17T13:32:37.380Z [GeneralBots] [32minfo[39m: Message [Obtendo tarefas do XRM...] sent to 5521979047667: {"sent":true,"message":"Sent to 5521979047667@c.us","id":"true_5521979047667@c.us_3EB044D89EF099EF81A1","queueNumber":5291}
2022-01-17T13:32:38.031Z [GeneralBots] [31merror[39m: ERROR: BASIC ERROR: 401 - "{\"status\":\"error\",\"message\":\"This hapikey doesn't exist.\",\"correlationId\":\"b278c4d2-c69c-4139-af0c-6e2c8b327943\"}"Stack:StatusCodeError: 401 - "{\"status\":\"error\",\"message\":\"This hapikey doesn't exist.\",\"correlationId\":\"b278c4d2-c69c-4139-af0c-6e2c8b327943\"}"at new StatusCodeError (D:\home\site\wwwroot\node_modules\request-promise-core\lib\errors.js:32:15)at Request.plumbing.callback (D:\home\site\wwwroot\node_modules\request-promise-core\lib\plumbing.js:104:33)at Request.RP$callback [as _callback] (D:\home\site\wwwroot\node_modules\request-promise-core\lib\plumbing.js:46:31)at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)at Request.emit (events.js:315:20)at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1154:10)at Request.emit (events.js:315:20)at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1076:12)at Object.onceWrapper (events.js:421:28)at IncomingMessage.emit (events.js:327:22)at endReadableNT (_stream_readable.js:1327:12)at processTicksAndRejections (internal/process/task_queues.js:80:21) Error: BASIC ERROR: 401 - "{\"status\":\"error\",\"message\":\"This hapikey doesn't exist.\",\"correlationId\":\"b278c4d2-c69c-4139-af0c-6e2c8b327943\"}"Stack:StatusCodeError: 401 - "{\"status\":\"error\",\"message\":\"This hapikey doesn't exist.\",\"correlationId\":\"b278c4d2-c69c-4139-af0c-6e2c8b327943\"}"at new StatusCodeError (D:\home\site\wwwroot\node_modules\request-promise-core\lib\errors.js:32:15)at Request.plumbing.callback (D:\home\site\wwwroot\node_modules\request-promise-core\lib\plumbing.js:104:33)at Request.RP$callback [as _callback] (D:\home\site\wwwroot\node_modules\request-promise-core\lib\plumbing.js:46:31)at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)at Request.emit (events.js:315:20)at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1154:10)at Request.emit (events.js:315:20)at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1076:12)at Object.onceWrapper (events.js:421:28)at IncomingMessage.emit (events.js:327:22)at endReadableNT (_stream_readable.js:1327:12)at processTicksAndRejections (internal/process/task_queues.js:80:21)at Function.callVM (D:\home\site\wwwroot\dist\packages\basic.gblib\services\GBVMService.js:740:19)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at async GBMinService.processMessageActivity (D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:817:17)at async D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:705:21
2022-01-17T13:32:38.047Z [GeneralBots] [32minfo[39m: Translated text(sendText): Lamento, ocorreu um erro que já foi registrado para ser tratado..
2022-01-17T13:32:39.363Z [GeneralBots] [32minfo[39m: Message [Lamento, ocorreu um erro que já foi registrado para ser tratado.] sent to 5521979047667: {"sent":true,"message":"Sent to 5521979047667@c.us","id":"true_5521979047667@c.us_3EB03BCFBE193BD78EAC","queueNumber":5292}
