### ISSUE TITLE
New KEYWORD CREATE DEAL

### ISSUE THREAD

**Issue by rodrigorodriguez** [GeneralBots/BotServer#181]
TALK "Qual o nome da Deal? Procure descrever o projeto em duas ou três palavras título." 

HEAR dealname 

TALK "Qual o nome do contato?" 

HEAR contato 

TALK "Qual o nome da empresa?" 

HEAR èmpresa 

TALK "Qual o valor desta oportunidade?" 

HEAR valor 

CREATE DEAL dealname, contato, empresa, valor

**Comment by PH-Nascimento** [comment]
@rodrigorodriguez ocorrendo erro para executar script:
![image](https://user-images.githubusercontent.com/42078703/149776262-4fef5766-e51e-476d-8075-bde59f697567.png)

2022-01-17T13:18:28.095Z [GeneralBots] [32minfo[39m: GBWhatsapp: RCV 5521979047667(): /call createdeal)
2022-01-17T13:18:29.501Z[GeneralBots] [32minfo[39m: User>: text:/call createdeal (type: message, name: undefined, channelId: webchat, value: undefined)
2022-01-17T13:18:29.849Z [GeneralBots] [31merror[39m: ERROR: INVALID BASIC CODE: Unexpected token 'this' evalmachine.<anonymous>:1
async function await this.createDeal(step) {^^^^
SyntaxError: Unexpected token 'this'at new Script (vm.js:100:7)at createScript (vm.js:261:10)at Object.runInContext (vm.js:292:10)at Function.callVM (D:\home\site\wwwroot\dist\packages\basic.gblib\services\GBVMService.js:719:16)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at async GBMinService.processMessageActivity (D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:817:17)at async D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:705:21 Error: INVALID BASIC CODE: Unexpected token 'this' evalmachine.<anonymous>:1async function await this.createDeal(step) {^^^^
SyntaxError: Unexpected token 'this'at new Script (vm.js:100:7)at createScript (vm.js:261:10)at Object.runInContext (vm.js:292:10)at Function.callVM (D:\home\site\wwwroot\dist\packages\basic.gblib\services\GBVMService.js:719:16)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at async GBMinService.processMessageActivity (D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:817:17)at async D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:705:21at Function.callVM (D:\home\site\wwwroot\dist\packages\basic.gblib\services\GBVMService.js:722:19)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at async GBMinService.processMessageActivity (D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:817:17)at async D:\home\site\wwwroot\dist\packages\core.gbapp\services\GBMinService.js:705:21
2022-01-17T13:18:29.876Z [GeneralBots] [32minfo[39m: Translated text(sendText): Lamento, ocorreu um erro que já foi registrado para ser tratado..
2022-01-17T13:18:31.072Z [GeneralBots] [32minfo[39m: Message [Lamento, ocorreu um erro que já foi registrado para ser tratado.] sent to 5521979047667: {"sent":true,"message":"Sent to 5521979047667@c.us","id":"true_5521979047667@c.us_3EB020EA72893060C0DF","queueNumber":5276}
